import type { Metadata } from 'next';
import './globals.css';
import Script from "next/script";
export const metadata: Metadata = {
  title: 'My New App',
  description: 'Generated by Onlook'
};
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <html lang="en" data-oid="eyp0:-w">
            <body className="" data-oid="nhqz21r">
                {children}
            
                <Script src="/builtwith.js" strategy="afterInteractive" />
            </body>
        </html>;
}